Controllers/CadeteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using tl2_tp5_2022_agussarroyoo.Models;
using tl2_tp5_2022_agussarroyoo.ViewModels;

namespace tl2_tp5_2022_agussarroyoo.Controllers
{
    [Route("[controller]/[action]")]
    public class CadeteController : Controller
    {
        private readonly ILogger<Cadete> _logger;
        private readonly IMapper _mapper;
        public static ICollection<Cadete> cadetes = new List<Cadete>();
        public static ICollection<CadeteViewModel> cadetesViewModel = new List<CadeteViewModel>();

        public CadeteController(ILogger<Cadete> logger, IMapper mapper)
        {
            _logger = logger;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }

        [HttpGet]
        public IActionResult Alta() {
            return View(new CadeteViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Alta(string nombre, string direc, long telefono) {
            Cadete cadete = new Cadete( nombre,  direc,  telefono);
            cadetes.Add(cadete);
            cadetesViewModel = _mapper.Map<List<CadeteViewModel>>(cadetes);

            return View("Listar", cadetesViewModel);
        }

        [HttpGet]
        public IActionResult Baja(int Id) {
            try
            {
              cadetes.Remove(BuscarPorId(Id));
              cadetesViewModel = _mapper.Map<List<CadeteViewModel>>(cadetes);

              return View("Listar", cadetesViewModel);

            }
            catch (System.Exception)
            {
                
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public IActionResult Edit(int Id) {
            return RedirectToAction("Editar",BuscarPorId(Id));
        }

        public IActionResult Editar(int Id) {
            CadeteViewModel cadete = _mapper.Map<CadeteViewModel>(BuscarPorId(Id));
            return View(cadete);
        }

        [HttpPost] 
        public IActionResult Editar(int id,string nombre, string direc, long telefono) {
            try
            {
                Cadete cadete = BuscarPorId(id);
                cadete.Nombre = nombre;
                cadete.Direccion = direc;
                cadete.Telefono = telefono;
                cadetesViewModel = _mapper.Map<List<CadeteViewModel>>(cadetes);

                return RedirectToAction("Listar");
            }
            catch (System.Exception)
            {
                
                return RedirectToAction("Index");
            }
            

        }
        public Cadete BuscarPorId(int id) {
            return cadetes.FirstOrDefault(x => x.ID == id);
        }

        public IActionResult Listar() {
            return View(cadetesViewModel);
        }

    }
}

Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using tl2_tp5_2022_agussarroyoo.Models;
using tl2_tp5_2022_agussarroyoo.ViewModels;
using AutoMapper;

namespace tl2_tp5_2022_agussarroyoo.Controllers
{
    [Route("[controller]/[action]")]
    public class PedidoController : Controller
    {
        private readonly ILogger<PedidoController> _logger;
        private readonly IMapper _mapper;
        public static ICollection<Pedido > pedidos = new List<Pedido>();
        public static ICollection<PedidoViewModel> _pedidosViewModel = new List<PedidoViewModel>();
        

        public PedidoController(ILogger<PedidoController> logger, IMapper mapper)
        {
            _logger = logger;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }

        [HttpGet("Alta")]
        public IActionResult Alta() {
            return View(new PedidoViewModel());
        }
         [HttpGet("Edit")]
        //Recibe la accion del boton Editar de la vista Listar y redirecciona a la vista Editar
        public IActionResult Edit(int Id) {
            return RedirectToAction("Editar", BuscarPorId(Id));
        }
        [HttpGet("Editar")]

        public IActionResult Editar(int Id) {
            PedidoViewModel pedido = _mapper.Map<PedidoViewModel>(BuscarPorId(Id));
            return View(pedido);
        }

        [HttpGet("Baja")]
        public IActionResult Baja(int Id) {
            try
            {
                pedidos.Remove(BuscarPorId(Id));
                _pedidosViewModel = _mapper.Map<List<PedidoViewModel>>(pedidos);

                return View("Listar",_pedidosViewModel);
            }
            catch (System.Exception)
            {
                
                return View("Index");
            }
            
        }

        [HttpPost("Alta")]
        [ValidateAntiForgeryToken]

        public IActionResult Alta(string obs, int idCliente, int idCadete) {
            Pedido nuevo = new Pedido(obs,idCliente,idCadete);
            pedidos.Add(nuevo);
            _pedidosViewModel = _mapper.Map<List<PedidoViewModel>>(pedidos);

            return View("Listar",_pedidosViewModel); 
        }
        [HttpPost("Editar")]
        public IActionResult Editar(int id,string obs, int idCliente, int idCadete) {
            try
            {
                Pedido actualizado = BuscarPorId(id);
                actualizado.Obs = obs;
                actualizado.IdCadete = idCadete;
                actualizado.IdCliente = idCliente;

                _pedidosViewModel = _mapper.Map<List<PedidoViewModel>>(pedidos);

                return RedirectToAction("Listar");

            }
            catch (System.Exception)
            {
                
                return View("Index");
            }

        }
        public IActionResult Listar() {
            return View(_pedidosViewModel);
        }

        public Pedido BuscarPorId(int id) {
            return pedidos.FirstOrDefault(x => x.id == id);
        }
    }
} 

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title class="title-marg">@ViewData["Title"] - tl2_tp4_2022_agussarroyoo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tl2_tp4_2022_agussarroyoo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tl2_tp4_2022_agussarroyoo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cadete" asp-action="Listar">Ver Cadetes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pedido" asp-action="Listar">Ver Pedidos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - tl2_tp4_2022_agussarroyoo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>